### ISSUE TITLE
Cannot go get

### ISSUE THREAD

**Issue by elisarver** [alittlebrighter/coach#1]
I pulled down your package with go get and found the following error:

`../../../go/src/github.com/alittlebrighter/coach/storage/database/bolt.go:120:2: missing return at end of function`

You might want to look into travis-ci (it's free!) to check for these sorts of issues on commit.

**Comment by alittlebrighter** [comment]
My apologies, stayed up too late making the last commit.  This is fixed and I added travis-ci.  Thanks for the suggestion.
